"""The MITRITY admission client.

Contract: https://github.com/mitrity-io/iag-specs/blob/main/sentinel/admission-api.md
Adapter guarantees: https://github.com/mitrity-io/iag-specs/blob/main/sentinel/adapters.md
"""

from ._canonical import canonical_json, config_hash
from ._client import (
    HEADER_TOKEN,
    HEADER_VERSION,
    MAX_REQUEST_BYTES,
    PROTOCOL_VERSION,
    UNREACHABLE_HINT,
    Client,
)
from ._config import (
    ATTEST_TIMEOUT,
    DEFAULT_HOLD_TIMEOUT,
    DEFAULT_TIMEOUT,
    ENV_ADDR,
    ENV_HOLD_TIMEOUT,
    ENV_TIMEOUT,
    ENV_TOKEN_FILE,
    HOLD_MARGIN,
    MAX_HOLD_TIMEOUT,
    MAX_TIMEOUT,
    Config,
    parse_duration,
    platform_defaults,
    split_addr,
    validate_addr,
)
from ._errors import (
    AdmissionConfigError,
    AdmissionError,
    AdmissionNotReady,
    AdmissionPayloadTooLarge,
    AdmissionProtocolError,
    AdmissionTimeout,
    AdmissionUnauthorized,
    AdmissionUnreachable,
)
from ._types import (
    ADAPTER_NAME,
    EXEC_CAPABLE_TOOLS,
    FRAMEWORK_FOR_SURFACE,
    AdmitRequest,
    Attestation,
    Decision,
    DecisionKind,
    SandboxPosture,
    Surface,
    Verdict,
)

__all__ = [
    "ADAPTER_NAME",
    "ATTEST_TIMEOUT",
    "DEFAULT_HOLD_TIMEOUT",
    "DEFAULT_TIMEOUT",
    "ENV_ADDR",
    "ENV_HOLD_TIMEOUT",
    "ENV_TIMEOUT",
    "ENV_TOKEN_FILE",
    "EXEC_CAPABLE_TOOLS",
    "FRAMEWORK_FOR_SURFACE",
    "HEADER_TOKEN",
    "HEADER_VERSION",
    "HOLD_MARGIN",
    "MAX_HOLD_TIMEOUT",
    "MAX_REQUEST_BYTES",
    "MAX_TIMEOUT",
    "PROTOCOL_VERSION",
    "UNREACHABLE_HINT",
    "AdmissionConfigError",
    "AdmissionError",
    "AdmissionNotReady",
    "AdmissionPayloadTooLarge",
    "AdmissionProtocolError",
    "AdmissionTimeout",
    "AdmissionUnauthorized",
    "AdmissionUnreachable",
    "AdmitRequest",
    "Attestation",
    "Client",
    "Config",
    "Decision",
    "DecisionKind",
    "SandboxPosture",
    "Surface",
    "Verdict",
    "canonical_json",
    "config_hash",
    "parse_duration",
    "platform_defaults",
    "split_addr",
    "validate_addr",
]
